services:
  webui:
    build: ./src/webui
    ports:
      - "3000:80"  # Mapear el puerto 3000 del host al puerto 80 del contenedor
    environment:
      NODE_ENV: production
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "3001:80"  # Mapea el puerto 3001 del host al puerto 80 del contenedor Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chat
      - generate
      - downloader
      - importer
      - settings
      - clean
      - dates
    networks:
      - app-network

  chat:
    build: ./src/microservices/chat
    ports:
      - "5001:5001"
    env_file: "docker.env"
    volumes:
      - server_data:/app/data  # Monta un volumen para persistir los datos del servidor
    networks:
      - app-network

  generate:
    build: ./src/microservices/generate
    ports:
      - "5002:5002"
    env_file: "docker.env"
    volumes:
      - server_data:/app/data  # Monta un volumen para persistir los datos del servidor
    networks:
      - app-network

  downloader:
    build: ./src/microservices/downloader
    ports:
      - "5003:5003"
    env_file: "docker.env"
    volumes:
      - server_data:/app/data  # Monta un volumen para persistir los datos del servidor
    networks:
      - app-network

  importer:
    build: ./src/microservices/importer
    ports:
      - "5004:5004"
    env_file: "docker.env"
    volumes:
      - server_data:/app/data  # Monta un volumen para persistir los datos del servidor
    networks:
      - app-network

  settings:
    build: ./src/microservices/settings
    ports:
      - "5005:5005"
    env_file: "docker.env"
    volumes:
      - server_data:/app/data  # Monta un volumen para persistir los datos del servidor
    networks:
      - app-network

  clean:
    build: ./src/microservices/clean
    ports:
      - "5006:5006"
    env_file: "docker.env"
    volumes:
      - server_data:/app/data  # Monta un volumen para persistir los datos del servidor
    networks:
      - app-network

  dates:
    build: ./src/microservices/dates
    ports:
      - "5007:5007"
    env_file: "docker.env"
    volumes:
      - server_data:/app/data  # Monta un volumen para persistir los datos del servidor
    networks:
      - app-network

  ollama:
    build: ./src/llm
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

volumes:
  ollama_data:  # Define el volumen para persistir los datos del servidor
  server_data:  

networks:
  app-network:
    driver: bridge
