server {
    listen 80;

    location /importer {
        proxy_pass http://flask_app:3001/importer;
    }

    location /downloader {
        proxy_pass http://flask_app:3001/downloader;
    }

    location /chat {
        proxy_pass http://flask_app:3001/chat;
    }

    location /settings {
        proxy_pass http://flask_app:3001/settings;
    }

    location /dates {
        proxy_pass http://flask_app:3001/dates;
    }

    location /generate {
        proxy_pass http://flask_app:3001/generate;
    }

    location /clean {
        proxy_pass http://flask_app:3001/clean;
    }
}
